### ISSUE TITLE
Discussion Group: Discovering Technical Needs for your Project!

### ISSUE THREAD

**Issue by hypernormal** [ProgressiveHackNight/breakout-groups#3]
### About the group
This will be a discussion/workshop group to help people or organizations with a project in mind figure out their technical needs. We will go through different exercises such a mapping out user journeys, service/tool discovery, and exploring currently existing solutions.

### Group leader/s
James Vaughan: vaughanj10@gmail.com

### Who we're looking for
People or organizations that have an idea for a tool that would be useful but still need to figure out the technical details of the tool before it can be developed. 

### Relevant Links
Open up a GitHub issue [here](https://github.com/ProgressiveHackNight/breakout-groups/issues/new?labels[]=discussion-group&title=Discussion%20Group:%20%3CYOUR%20TITLE%20HERE%3E) and answer these questions before coming in with your idea

### Where we meet
We will be meeting by the tables near the couches in the back right.

**Comment by rapicastillo** [comment]
Will close this for!
