### ISSUE TITLE
2017/04/12 Project Swimmy at Progressive Hack Night

### ISSUE THREAD

**Issue by geoffreyyip** [ProgressiveHackNight/breakout-groups#5]
## About the group
At its core, Project Swimmy is an events search platform that connects activists with local organizing groups. More broadly, Project Swimmy exists to enable people who are confronting the need for change to collectively organize. Swimmy aims to build power in communities by bringing people together in groups and building on coalitions and intersection of issues.

## Group leader
Geoffrey Yip

## Who we're looking for
Front End Developers with React and/ or MobX knowledge.

And someone who knows how to host through GitHub Pages.

#### 1. Fixing React Hot Reloader. 

This should be quick. Hopefully. I need a developer or two to figure out how React Hot Reloader works with mobx-react's <Provider> element and react-router. Ideally, we get this done in an hour or two.

#### 2. Making a GitHub Pages demo off of our `develop/` branch

It's not easy to see the current version of Project Swimmy. Even if you know how to code, you still have to fork the repo, install the modules, and run a dev server. And if you don't know how to code, you can't see it at all. 

Your job will be to host the current production build through GitHub pages.

#### 3. Technical write-up on RootStore pattern.

It's not obvious what design pattern we're using until you look inside the `src/stores/rootStore.js` file, then navigate to the [url](https://github.com/mobxjs/mobx/issues/300) defined inside there, then read the comments, and then find the comment talking about the RootStore. You have to do all that to really understand what the rootStore is, or what syntax you need to use.

Your job will be to digest the rootStore pattern is used within our app in the context of the @inject/ @Provider/ @observer decorator syntax, and produce a README.md doc that new developers can understand within an hour. Make sure it's understandable by a junior developer.

Here's some docs that may help: https://mobx.js.org/best/store.html

#### 4. Explore the code base and find what's confusing.

There are different holes in our knowledge. Things that may be obvious to me may not be obvious to others. Your job will be to get a local repository on your computer, go through the codebase and see what's confusing/ frustrating about the project. A positive developer experience is important.

Comments can be written here directly on the issue, or sent anonymously to my ProgCode Slack handle @geoffreyyip .

## Relevant Links
[Official README.md](https://github.com/SwimmyApp/project-swimmy-mockup)
UI Mockup, Trello Board, and official Google Drive Welcome doc are in there.

**What stage is the project at? (Ideation, implementation, or beta?)**

We're in implementation stage. We have a UI Mockup, and we're developing our MVP off of it.

**What is the problem you are trying to solve, and why is it a problem?**

Open-source projects are always difficult to get started with. It takes time to familiarize oneself with the software stack, the code base, and the design patterns. Today is designed to document 

**How does this tie into the ProgCode ecosystem?**

I'm still figuring this part out. We're not the only ones that are talking about an events-search platform. It's possible that our idea gets integrated or even absorbed into another project. That's still to be determined. For now, our main goal is to get this prototype done.

**Comment by rapicastillo** [comment]
@geoffreyyip I'm closing this as there hasnt been activity on this. Please feel free to reopen
