### ISSUE TITLE
Discussion Group: ProgHackNight Onboarding

### ISSUE THREAD

**Issue by rcscastillo** [ProgressiveHackNight/breakout-groups#6]
### About the group

I'd like to setup a discussion on what the hack night is about, how to effectively engage with the community, and answer any questions you may have!

### Group leader/s
Rapi!

### Who we're looking for
Folks who want to learn more about the Progressive Hack Night, learn how to maximize things.

### Tools
-

### Relevant Links
www.proghacknight.org

### Where we meet
By the couch!

**Comment by rapicastillo** [comment]
Closing this for now!
